#!/bin/bash

echo "🔍 Test des corrections de redirection après connexion"
echo "======================================================"

echo ""
echo "✅ Services backend actifs :"
echo "   - Auth: http://localhost:8080"
echo "   - Profile: http://localhost:8081"
echo "   - Interactions: http://localhost:8082"

echo ""
echo "✅ Frontend actif :"
echo "   - Local: http://localhost:5176"
echo "   - Network: http://157.180.36.122:5176"

echo ""
echo "🎯 TESTS À EFFECTUER MANUELLEMENT :"
echo ""
echo "1. Ouvrez http://localhost:5176 ou http://157.180.36.122:5176"
echo "2. Cliquez sur 'Se connecter'"
echo "3. Utilisez les identifiants :"
echo "   📧 Email: test@example.com"
echo "   🔑 Password: password123"
echo ""
echo "4. Vérifiez que :"
echo "   ✅ La connexion réussit (HTTP 200)"
echo "   ✅ Vous êtes redirigé vers /app au lieu de rester sur /login"
echo "   ✅ Si l'email n'est pas vérifié, vous êtes redirigé vers /verify-email"
echo ""
echo "📝 CORRECTIONS APPORTÉES :"
echo "   - Ajout de l'intercepteur d'authentification pour authApi"
echo "   - Lecture des tokens depuis localStorage au lieu de variables globales"
echo "   - Gestion des utilisateurs non vérifiés dans useAuth"
echo "   - Redirection automatique vers /verify-email si email non vérifié"
echo "   - Mise à jour de ProtectedRoute pour détecter les utilisateurs temporaires"
echo ""
echo "🔧 Si vous rencontrez des problèmes :"
echo "   - Vérifiez la console du navigateur (F12)"
echo "   - Regardez les logs du backend : docker-compose logs -f wayd-auth"
echo "   - Nettoyez le localStorage si nécessaire"
